import { ITableDTO } from "./dto.ts";

export const data: ITableDTO[] = [
  {
    ID: "12",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
  {
    ID: "123",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
  {
    ID: "1234",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
  {
    ID: "12345",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
  {
    ID: "123456",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
  {
    ID: "12345612332323",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
  {
    ID: "12345236",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
  {
    ID: "123412356",
    Login: "Login",
    Percent: 42,
    Profit: 545,
    Balance: 123,
    Date: new Date(),
    IsInWork: true,
  },
];
